name: Start Site
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Manual Start Site'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: xcratch/scratch-gui
          ref: xcratch
          path: ./scratch-gui
      - run: npm install
        working-directory: ./scratch-gui
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/mbit-more-v2
          ref: master
          path: ./mbit-more-v2
      - run: node ./scripts/register.js --id=microbitMore --gui=../scratch-gui --url="https://microbit-more.github.io/dist/microbitMore.mjs" -C
        working-directory: ./mbit-more-v2
      - run: npm install
        working-directory: ./mbit-more-v2
      - run: rm -rf ./dist && mkdir -p ./dist
        working-directory: ./mbit-more-v2
      - run: node ./scripts/build.js --name=microbitMore --url="https://microbit-more.github.io/dist/microbitMore.mjs" --block=./src/block --entry=./src/entry --vm=../scratch-gui/node_modules/scratch-vm --gui=../scratch-gui --output=./dist
        working-directory: ./mbit-more-v2
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/microbit-more.github.io
          ref: main
          path: ./microbit-more.github.io
      - run: node ./scripts/tailoring.js -gui=../scratch-gui
        working-directory: ./microbit-more.github.io
      - run: npm run build
        working-directory: ./scratch-gui
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/microbit-more.github.io
          path: ./microbit-more.github.io
      - run: mv -T ./microbit-more.github.io/site ./public
      - run: mv -T ./scratch-gui/build ./public/editor
      - run: mv -T ./mbit-more-v2/dist ./public/dist
      - run: mv -T ./mbit-more-v2/examples ./public/examples
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/microbit-more-doc
          path: ./microbit-more-doc
      - run: mv -T ./microbit-more-doc/docs ./public/docs
      - run: mv -T ./microbit-more-doc/docs-ja ./public/docs-ja
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: .
          keep_files: false
