name: Start Dev Site
on:
  push:
    branches:
      - develop
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: yokobond/scratch-gui
          ref: xcratch
          path: ./scratch-gui
      - run: npm install
        working-directory: ./scratch-gui
      - uses: actions/checkout@v2
        with:
          repository: yokobond/mbit-more-v2
          ref: develop
          path: ./mbit-more-v2
      - run: node ./scripts/register.js --id=microbitMore --gui=../scratch-gui --url="https://yokobond.github.io/mbit-more-v2/dev/dist/microbitMore.mjs" -C
        working-directory: ./mbit-more-v2
      - run: npm install
        working-directory: ./mbit-more-v2
      - run: rm -rf ./dist && mkdir -p ./dist
        working-directory: ./mbit-more-v2
      - run: node ./scripts/build.js --name=microbitMore --url="https://yokobond.github.io/mbit-more-v2/dev/dist/microbitMore.mjs" --block=./src/block --entry=./src/entry --vm=../scratch-gui/node_modules/scratch-vm --gui=../scratch-gui --output=./dist
        working-directory: ./mbit-more-v2
      - run: node ./scripts/change-logo.js -gui=../scratch-gui
        working-directory: ./mbit-more-v2
      - run: npm run build
        working-directory: ./scratch-gui
      - run: cp ./mbit-more-v2/site/index.html ./scratch-gui/build/index.html
      - run: cp ./mbit-more-v2/site/favicon.ico ./scratch-gui/build/static/favicon.ico
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/microbit-more.github.io
          path: ./microbit-more.github.io
      - run: mv -T ./microbit-more.github.io/site ./public
      - run: mv -T ./scratch-gui/build ./public/editor
      - run: mv -T ./mbit-more-v2/dist ./public/dist
      - run: mv -T ./mbit-more-v2/examples ./public/examples
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/microbit-more-doc
          path: ./microbit-more-doc
      - run: mv -T ./microbit-more-doc/docs ./public/docs
      - run: mv -T ./microbit-more-doc/docs-ja ./public/docs-ja
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./dev
          keep_files: false
